### ISSUE TITLE
Is this plugin "ready"?

### ISSUE THREAD

**Issue by peteeveleigh** [putyourlightson/craft-commerce-worldpay-access#1]
Hi Ben,

Just wondering if this plugin is ready? It doesn't appear on the plugin store.
Also wondering if it's a drop in replacement for the Worldpay Gateway plugin and if it supports 3DS2 etc (which the first-party Worldpay Gateway plugin does not since it uses Omnipay)

Pete

**Comment by bencroker** [comment]
We built this plugin when Worldpay Access was relatively new, so were holding off on releasing the plugin until we were sure it was stable. The plugin is being used in production on at least one site, so it should be usable, but I can't guarantee anything until it is released into the plugin store. As for when that might happen, there are no immediate plans, but if then some time in Q1 2022. If you have an urgent need for it, as well as some budget, then I can try to prioritise it as much as possible.

The plugin is not a drop-in replacement, but it supports 3DS with Worldpay Access.

**Comment by gazlawn22** [comment]
Are you likely to be releasing this plugin, and if so, would you release for Craft 3 now or just look at a Craft 4 release?

**Comment by bencroker** [comment]
No immediate plans to release it in the plugin store, as it needs further testing and I have no real-world use-case currently.
